### ISSUE TITLE
Some concerning about the slime chunk cracking tool

### ISSUE THREAD

**Issue by vohai2003** [Badel2/slime_seed_finder#36]
Hi.
Does the slime chunk cracking tool support cracking for lastest version (1.19)?
And is web version the lastest version of the tool?

**Comment by Badel2** [comment]
Hi, the slime chunk tool supports all the versions that have slime chunks, because the algorithm has never changed. So 1.19 should work fine. But only Java edition, it does not support Bedrock edition.

And all the web apps are always the latest version of the tool, they use the code of the master branch.

**Comment by vohai2003** [comment]
> Hi, the slime chunk tool supports all the versions that have slime chunks, because the algorithm has never changed. So 1.19 should work fine. But only Java edition, it does not support Bedrock edition.
> 
> And all the web apps are always the latest version of the tool, they use the code of the master branch.

So I have quite a problem. My server owner published the slime chunks map of the world. But when I inputed the 16x16 slime chunk starting from (0,0) the app just showed "0*2^30 candidates" and not running.
What're the possible situations that can cause this behaviour?
![unknown](https://user-images.githubusercontent.com/63694226/188272960-119b0181-dd59-4575-ae4e-0f3a25d637e2.png)

**Comment by Badel2** [comment]
Hi, the most likely cause is that you made a mistake when entering the data. Even 1 wrong chunk can break the program. So first of all, double check that the chunks are correct. Below the map you can see a text that says something like "Chunk x: 6, z: -10 --- Block x: 99, z: -147". These are the chunk and block coordinates of where is the mouse, you can compare the block coordinates with the coordinates of the screenshot you posted.
