### ISSUE TITLE
Multi-Spawner finder crashes 

### ISSUE THREAD

**Issue by 281732** [Badel2/slime_seed_finder#37]
I have tried running it several times on both firefox and chromium but it always results in an error
![image](https://github.com/Badel2/slime_seed_finder/assets/121222332/f09da58e-3531-46e3-aa28-35e5525716e8)

**Comment by Badel2** [comment]
Hi, this probably means that you have a corrupted chunk. Are you on a snapshot or using mods? You can try to workaround it by limiting the search to a smaller area.

Under " Show advanced options ", set "Search radius" to 20 and "Center coordinates" to 0,0,0 for example. You can then change the center coordinates to search other parts of your world.

I also updated dependencies in case that helps.

**Comment by 281732** [comment]
Thank you for the quick response!

The chunks must have been corrupted, after regenerating the world with a pre-generator the issue has not occurred again.
