### ISSUE TITLE
The -i parameter is required

### ISSUE THREAD

**Issue by NaNraptor** [Badel2/slime_seed_finder#7]
Under Usage there is the following command listed:

```slime_seed_finder -s 1234 -o 1234.txt```

This will not work as the -i param is not specified, which seems to be required, a workaround is to just create an empty .txt file and do:

```slime_seed_finder -s 1234 -o 1234.txt -i ./empty.txt```

**Comment by Badel2** [comment]
All those flags were getting out of control... The new command for generating slime chunks is:

    slime_seed_finder generate --num-slime-chunks=20 --seed=1234 -o seedinfo1234.json

Much better, isn't it?
